[package]
name = "hyper_http_custom_transport"
version = "0.1.0"
edition = "2018"

[dependencies]
#hyper = {version = "0.14", features = ["full"], path="hyper"}
hyper = {version = "0.14", features = ["full"]}
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.4.0"